var dir_9b25e8bdfd744a8dbcf057a505b724bf =
[
    [ "axisglwidget.cpp", "axisglwidget_8cpp_source.html", null ],
    [ "axisglwidget.h", "axisglwidget_8h_source.html", null ],
    [ "axisgroupbox.cpp", "axisgroupbox_8cpp_source.html", null ],
    [ "axisgroupbox.h", "axisgroupbox_8h_source.html", null ],
    [ "dimensionsgroupbox.cpp", "dimensionsgroupbox_8cpp_source.html", null ],
    [ "dimensionsgroupbox.h", "dimensionsgroupbox_8h_source.html", null ],
    [ "download.cpp", "download_8cpp_source.html", null ],
    [ "glmdichild.cpp", "glmdichild_8cpp_source.html", null ],
    [ "glmdichild.h", "glmdichild_8h_source.html", null ],
    [ "glwidget.cpp", "glwidget_8cpp_source.html", null ],
    [ "glwidget.h", "glwidget_8h_source.html", null ],
    [ "main.cpp", "main_8cpp_source.html", null ],
    [ "meshinformationgroupbox.cpp", "meshinformationgroupbox_8cpp_source.html", null ],
    [ "meshinformationgroupbox.h", "meshinformationgroupbox_8h_source.html", null ],
    [ "propertiesgroupbox.cpp", "propertiesgroupbox_8cpp_source.html", null ],
    [ "propertiesgroupbox.h", "propertiesgroupbox_8h_source.html", null ],
    [ "stlcompare.cpp", "stlcompare_8cpp_source.html", null ],
    [ "stlcompare.h", "stlcompare_8h_source.html", null ],
    [ "stlfile.cpp", "stlfile_8cpp_source.html", null ],
    [ "stlfile.h", "stlfile_8h_source.html", null ],
    [ "stlsphere.cpp", "stlsphere_8cpp_source.html", null ],
    [ "stlsphere.h", "stlsphere_8h_source.html", null ],
    [ "stlviewer.cpp", "stlviewer_8cpp_source.html", null ],
    [ "stlviewer.h", "stlviewer_8h_source.html", null ],
    [ "types.h", "types_8h_source.html", null ],
    [ "vector.cpp", "vector_8cpp_source.html", null ],
    [ "vector.h", "vector_8h_source.html", null ]
];